import { defineConfig } from 'wxt';

/**
 * E2E-only escape hatch: `ADSDIM_E2E=1 wxt build` additionally matches the
 * Playwright fixture server on localhost. A normal `wxt build` (any value
 * other than exactly '1') ships x.com/twitter.com matches only — asserted
 * by e2e/tests/manifest.spec.ts.
 */
const E2E_EXTRA_MATCHES =
  process.env.ADSDIM_E2E === '1' ? ['http://localhost/*', 'http://127.0.0.1/*'] : [];

/**
 * AdsDim — marks ads on the x.com timeline, never hides posts.
 * See https://wxt.dev/api/config.html
 */
export default defineConfig({
  // Explicit imports only; keeps the code greppable and unit-testable.
  imports: false,
  modules: ['@wxt-dev/module-react'],
  manifest: {
    name: 'AdsDim',
    description:
      'Dim the ads, let real posts shine. Marks ads on the x.com timeline without ever hiding posts.',
    permissions: ['storage'],
    // Generated by scripts/generate-icons.mjs (reproducible SVG -> PNG render).
    icons: {
      16: 'icon/16.png',
      32: 'icon/32.png',
      48: 'icon/48.png',
      96: 'icon/96.png',
      128: 'icon/128.png',
    },
    action: {
      default_icon: {
        16: 'icon/16.png',
        32: 'icon/32.png',
        48: 'icon/48.png',
      },
    },
  },
  hooks: {
    'build:manifestGenerated': (_wxt, manifest) => {
      if (E2E_EXTRA_MATCHES.length === 0) return;
      for (const script of manifest.content_scripts ?? []) {
        // WXT hands hooks the generated manifest for in-place amendment.
        script.matches = [...(script.matches ?? []), ...E2E_EXTRA_MATCHES];
      }
    },
  },
});
